Added content to Matches page
paprika-spice/web-app pull request #49
Opened 2018-02-27 15:36 UTC by TeriDibbits

Added default layout using Jekyll
Added card from the style tile html
stylized cards
added change button and content
resized images in images folder to fit cards

2018-02-28 19:31 UTC, MJholland requested changes
Everything looks good I just think the very last div needs a push-2 class instead so it's end space is more definitive.

2018-02-28 20:10 UTC, MJholland requested changes
Also everything in the html should be wrapped in a main as part of best practices.

2018-03-02 16:00 UTC, TeriDibbits commented
I fixed the requested changes and added a media query to removed extra space on the image in larger screen sizes.

2018-03-05 17:08 UTC, MJholland approved these changes

2018-03-05 17:08 UTC, merged